import {
  textField,
  numberField,
  radioField,
  checkboxField,
  selectField,
  btnSingleField,
  dateField,
} from "./InputFields";

export const formField = {
  text: textField,
  number: numberField,
  radio: radioField,
  checkbox: checkboxField,
  select: selectField,
  btnSingle: btnSingleField,
  date: dateField,
};

export const imageTypes = [
  "Main Image",
  "Exterior View",
  "Living Room",
  "Bedrooms",
  "Bathrooms",
  "Washrooms",
  "Kitchen",
  "Floor Plan",
  "Master Plan",
  "Common Area",
  "Location Map",
  "Site View",
  "Brochure",
  "Others",
];

export const keyMap = {
  // common
  postingAs: "iam",
  postFor: "postFor",
  name: "name",
  email: "email",
  mobile: "mobile",
  for: "forr",
  type: "property_type",
  address: "address",
  city: "city",
  locality: "locality",
  nearByLocation1: "locality2",
  nearByLocation2: "locality3",
  nearByLocation3: "locality4",
  nearByLocation4: "locality5",
  latitude: "latitude",
  longitude: "longitude",
  reraNo: "rera_id",
  // propertyDetails
  projectName: "project_name",
  landZone: "land_zone",
  idealForBusinesses: "ideal_business",
  nearbyBusinesses: "near_by",
  // propertyFeatures
  bedrooms: "bedroom",
  bathrooms: "bathroom",
  balconies: "balconies",
  floorNo: "floor_no",
  totalFloors: "total_floor",
  furnishedStatus: "furnish_status",
  floorsAllowed: "floors_alloww",
  noOfOpenSides: "open_side",
  widthOfRoadFacing: "width_road",
  anyConstructionDone: "any_con",
  boundaryWallMade: "wall_made",
  isInAGatedColony: "colony",
  washrooms: "washrooms",
  personalWashroom: "per_washroom",
  pantryCafeteria: "pantry",
  willingToModifInteriors: "willing_to",
  lockinPeriod: "lockin",
  cornerShop: "corner_shop",
  isMainRoadFacing: "main_road",
  cornerShowroom: "corner_showroom",
  // area
  areaIn: "area_unit",
  superArea: "super_area",
  builtupArea: "built_area",
  carpetArea: "carpet_area",
  coveredArea: "covered_area",
  widthOfEntrance: "width_entrace",
  plotArea: "plot_area",
  plotLength: "plot_length",
  plotBreadth: "plot_breadth",
  isCornerPlot: "corner",
  // transactionType
  transactionType: "transaction_type",
  possessionStatus: "prop_availability",
  availableFrom: "avai_from_year",
  ageOfConstruction: "age_of_con",
  // priceDetails
  expectedPrice: "exp_price",
  priceInWord: "price_words",
  pricePerSqft: "price_per",
  pricePerSqYrd: "price_per_sqyrd",
  otherCharges: "otc_chrg",
  stampDutyCharges: "registration_charge",
  bookingOrTokenAmount: "booking_amt",
  maintenanceCharge: "maintainance",
  maintenancePer: "per",
  monthlyRent: "monthly_rent",
  electricityCharges: "electricity_water",
  depositAmount: "security_amt",
  // carParking
  youtubeLink: "youtubeLink",
  carParking: "car_parking",
  multiUnitAvai: "multi_unit",
  overlooking: "overlookng",
  // statusOfWaterAndElectricity
  availOfWater: "avail_water",
  statusOfElec: "electricity",
  ownershipStatus: "ownership_status",
  // plotApprovalAuthority
  plotApprovalAuthority: "appr_authority",
  approvedBy: "approved_by",
  // connectivity
  connectivity: "connectivity",
  within2km: "connectivity_within",
  within5km: "conn_within1",
  within10km: "conn_within2",
  // flooring
  flooring: "flooring",
  // amenities
  amenities: "amenities",
  extraAmenities: "extraAmenities",
  // descriptionAndLandmarks
  interestingPropertyDetails: "int_prop_detail",
  landmarksAndNeighbourhood: "landmark_neigh",
};

export const step1Fields = {
  postingAs: "",
  postFor: "B2C",
  name: "",
  email: "",
  mobile: "",
  for: "",
  type: "",
  address: "",
  city: "",
  locality: "",
  nearByLocation1: "",
  nearByLocation2: "",
  nearByLocation3: "",
  nearByLocation4: "",
  reraNo: "",
  // propertyDetails
  projectName: "",
  landZone: "",
  idealForBusinesses: "",
  nearbyBusinesses: "",
  // propertyFeatures
  bedrooms: "",
  bathrooms: "",
  balconies: "0",
  floorNo: "",
  totalFloors: "",
  furnishedStatus: "",
  floorsAllowed: "",
  noOfOpenSides: "",
  widthOfRoadFacing: "",
  anyConstructionDone: "",
  boundaryWallMade: "",
  isInAGatedColony: "",
  washrooms: "",
  personalWashroom: "",
  pantryCafeteria: "",
  willingToModifInteriors: "",
  lockinPeriod: "",
  cornerShop: "",
  isMainRoadFacing: "",
  cornerShowroom: "",
  // area
  areaIn: "",
  superArea: "",
  builtupArea: "",
  carpetArea: "",
  coveredArea: "",
  widthOfEntrance: "",
  plotArea: "",
  plotLength: "",
  plotBreadth: "",
  isCornerPlot: "",
  // transactionType
  transactionType: "",
  possessionStatus: "",
  availableFrom: "",
  ageOfConstruction: "",
  // priceDetails
  expectedPrice: "",
  priceInWord: " ",
  pricePerSqft: "",
  pricePerSqYrd: "",
  otherCharges: "",
  stampDutyCharges: "",
  bookingOrTokenAmount: "",
  maintenanceCharge: "",
  maintenancePer: "Monthly",
  monthlyRent: "",
  electricityCharges: "",
  depositAmount: "",
};

export const step2Fields = {
  youtubeLink: "",
  // carParking
  carParking: "",
  multiUnitAvai: "",
  overlooking: "",
  // statusOfWaterAndElectricity
  availOfWater: "",
  statusOfElec: "",
  ownershipStatus: "",
  // plotApprovalAuthority
  plotApprovalAuthority: "",
  approvedBy: "",
  // connectivity
  connectivity: "",
  within2km: "",
  within5km: "",
  within10km: "",
  // flooring
  flooring: "",
  // amenities
  amenities: "",
  extraAmenities: "",
  // descriptionAndLandmarks
  interestingPropertyDetails: "",
  landmarksAndNeighbourhood: "",
};

export const fieldData = {
  projectName: {
    key: "projectName",
    type: "text",
    label: "Name of Project/Society",
    value: "",
  },
  postingAs: {
    key: "postingAs",
    type: "radio",
    label: "You are posting as",
    options: ["Full House", "On Sharing Basis"],
    value: "",
  },
  landZone: {
    key: "landZone",
    type: "select",
    label: "Land Zone",
    options: [
      "Industrial",
      "Commercial",
      "Residential",
      "Transport and Communication",
      "Public Utilities",
      "Public and Semi Public Use",
      "Open Spaces",
      "Agricultural Zone",
      "Special Economic Zone",
      "Natural Conservation Zone",
      "Government Use",
    ],
    value: "",
  },
  idealForBusinesses: {
    key: "idealForBusinesses",
    type: "text",
    label: "Ideal For Businesses",
    value: "",
  },
  nearbyBusinesses: {
    key: "nearbyBusinesses",
    type: "text",
    label: "Nearby Businesses",
    value: "",
  },
  bedrooms: {
    key: "bedrooms",
    type: "btnSingle",
    label: "Bedrooms",
    options: Array.from({ length: 10 }, (_, i) => i + 1),
    value: "",
  },
  bathrooms: {
    key: "bathrooms",
    type: "btnSingle",
    label: "Bathrooms",
    options: Array.from({ length: 10 }, (_, i) => i + 1),
    value: "",
  },
  balconies: {
    key: "balconies",
    type: "btnSingle",
    label: "Balconies",
    options: Array.from({ length: 11 }, (_, i) => i),
    value: "",
  },
  floorNo: {
    key: "floorNo",
    type: "select",
    label: "Floor No.",
    options: [
      "Lower",
      "BasementUpper",
      "BasementGround",
      ...Array.from({ length: 200 }, (_, i) => i + 1),
    ],
    value: "",
  },
  totalFloors: {
    key: "totalFloors",
    type: "select",
    label: "Total Floors",
    options: Array.from({ length: 200 }, (_, i) => i + 1),
    value: "",
  },
  furnishedStatus: {
    key: "furnishedStatus",
    type: "btnSingle",
    label: "Furnished Status",
    options: ["Furnished", "Unfurnished", "Semi-Furnished"],
    value: "",
  },
  floorsAllowed: {
    key: "floorsAllowed",
    type: "select",
    label: "Floors Allowed For Construction",
    options: Array.from({ length: 20 }, (_, i) => i + 1),
    value: "",
  },
  noOfOpenSides: {
    key: "noOfOpenSides",
    type: "btnSingle",
    label: "No Of Open Sides",
    options: [1, 2, 3, 4],
    value: "",
  },
  widthOfRoadFacing: {
    key: "widthOfRoadFacing",
    type: "text",
    label: "Width Of Road Facing The Plot",
    value: "",
  },
  anyConstructionDone: {
    key: "anyConstructionDone",
    type: "radio",
    label: "Any Construction Done",
    options: ["Yes", "No"],
    value: "",
  },
  boundaryWallMade: {
    key: "boundaryWallMade",
    type: "radio",
    label: "Boundary Wall Made",
    options: ["Yes", "No"],
    value: "",
  },
  isInAGatedColony: {
    key: "isInAGatedColony",
    type: "radio",
    label: "Is in a Gated Colony",
    options: ["Yes", "No"],
    value: "",
  },
  washrooms: {
    key: "washrooms",
    type: "btnSingle",
    label: "Washrooms",
    options: Array.from({ length: 10 }, (_, i) => i + 1),
    value: "",
  },
  personalWashroom: {
    key: "personalWashroom",
    type: "radio",
    label: "Personal Washroom",
    options: ["Yes", "No"],
    value: "",
  },
  pantryCafeteria: {
    key: "pantryCafeteria",
    type: "radio",
    label: "Pantry/Cafeteria",
    options: ["Dry", "Wet", "Not Available"],
    value: "",
  },
  willingToModifInteriors: {
    key: "willingToModifInteriors",
    type: "radio",
    label: "Willing to modify interiors",
    options: ["Yes", "No"],
    value: "",
  },
  lockinPeriod: {
    key: "lockinPeriod",
    type: "number",
    label: "Lock-in Period (In Years)",
    value: "",
  },
  cornerShop: {
    key: "cornerShop",
    type: "radio",
    label: "Corner Shop",
    options: ["Yes", "No"],
    value: "",
  },
  isMainRoadFacing: {
    key: "isMainRoadFacing",
    type: "radio",
    label: "Is Main Road Facing",
    options: ["Yes", "No"],
    value: "",
  },
  cornerShowroom: {
    key: "cornerShowroom",
    type: "radio",
    label: "Corner Showroom",
    options: ["Yes", "No"],
    value: "",
  },
  areaIn: {
    key: "areaIn",
    type: "select",
    label: "Area In",
    options: [
      "Sq-ft",
      "Sq-yrd",
      "Sq-m",
      "Acre",
      "Bigha",
      "Hectare",
      "Marla",
      "Kanal",
      "Biswa1",
      "Biswa2",
      "Ground",
      "Aankadam",
      "Rood",
      "Chatak",
      "Kottah",
      "Marla",
      "Cent",
      "Perch",
      "Guntha",
      "Are",
    ],
    value: "",
  },
  superArea: {
    key: "superArea",
    type: "number",
    label: "Super Area",
    value: "",
  },
  builtupArea: {
    key: "builtupArea",
    type: "number",
    label: "Built-up Area",
    value: "",
  },
  carpetArea: {
    key: "carpetArea",
    type: "number",
    label: "Carpet Area",
    value: "",
  },
  coveredArea: {
    key: "coveredArea",
    type: "number",
    label: "Covered Area",
    value: "",
  },
  widthOfEntrance: {
    key: "widthOfEntrance",
    type: "number",
    label: "Width Of Entrance(ft)",
    value: "",
  },
  plotArea: {
    key: "plotArea",
    type: "number",
    label: "Plot Area",
    value: "",
  },
  plotLength: {
    key: "plotLength",
    type: "number",
    label: "Plot Length",
    value: "",
  },
  plotBreadth: {
    key: "plotBreadth",
    type: "number",
    label: "Plot Breadth",
    value: "",
  },
  isCornerPlot: {
    key: "isCornerPlot",
    type: "checkbox",
    label: "",
    options: ["This is a Corner Plot"],
    value: "",
  },
  transactionType: {
    key: "transactionType",
    type: "radio",
    label: "Listing Type",
    options: ["New Property", "Resale"],
    value: "",
  },
  possessionStatus: {
    key: "possessionStatus",
    type: "radio",
    label: "Possession Status",
    options: ["Under Construction", "Ready to Move"],
    value: "",
  },
  availableFrom: {
    key: "availableFrom",
    type: "date",
    hide: true,
    label: "Available From",
    value: "",
  },
  ageOfConstruction: {
    key: "ageOfConstruction",
    type: "select",
    hide: true,
    label: "Age Of Construction",
    options: [
      "New Construction",
      "Less than 5 years",
      "5 to 10 years",
      "10 to 15 years",
      "15 to 20 years",
      "Above 20 years",
    ],
    value: "",
  },
  expectedPrice: {
    key: "expectedPrice",
    type: "number",
    label: "Expected Price",
    value: "",
  },
  priceInWord: {
    key: "priceInWord",
    type: "text",
    label: "Expected Price In Word",
    value: "",
  },
  pricePerSqft: {
    key: "pricePerSqft",
    type: "number",
    label: "Price Per Sq-ft",
    value: "",
  },
  pricePerSqYrd: {
    key: "pricePerSqYrd",
    type: "number",
    label: "Price Per Sq-Yrd",
    value: "",
  },
  otherCharges: {
    key: "otherCharges",
    type: "text",
    label: "Other Charges",
    value: "",
  },
  stampDutyCharges: {
    key: "stampDutyCharges",
    type: "checkbox",
    label: "",
    options: ["Stamp Duty And Registration Charges Excluded"],
    value: "",
  },
  bookingOrTokenAmount: {
    key: "bookingOrTokenAmount",
    type: "text",
    label: "Booking Or Token Amount",
    value: "",
  },
  maintenanceCharge: {
    key: "maintenanceCharge",
    type: "number",
    label: "maintenance Charge",
    value: "",
  },
  maintenancePer: {
    key: "maintenancePer",
    type: "select",
    label: "Maintenance Per",
    options: [
      "Monthly",
      "Quarterly",
      "Yearly",
      "One-Time",
      "Per sq. Unit Monthly",
    ],
    value: "Monthly",
  },
  monthlyRent: {
    key: "monthlyRent",
    type: "number",
    label: "Monthly Rent",
    value: "",
  },
  electricityCharges: {
    key: "electricityCharges",
    type: "checkbox",
    label: "",
    options: ["Electricity And Water Charges Excluded"],
    value: "",
  },
  depositAmount: {
    key: "depositAmount",
    type: "number",
    label: "Deposit Amount",
    value: "",
  },
};

export const step1FormFields = {
  "Flat/Apartment": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "superArea",
      "builtupArea",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "superArea",
      "builtupArea",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Residential House": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  Villa: {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Builder Floor Apartment": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  Penthouse: {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Studio Apartment": {
    Sale: [
      "projectName",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Service Apartment": {
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Residential Land/Plot": {
    Sale: [
      "projectName",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "anyConstructionDone",
      "boundaryWallMade",
      "isInAGatedColony",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
    ],
  },
  "Commercial Office Space": {
    Sale: [
      "projectName",
      "landZone",
      "idealForBusinesses",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "areaIn",
      "carpetArea",
      "coveredArea",
      "plotArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "depositAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "idealForBusinesses",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "lockinPeriod",
      "carpetArea",
      "coveredArea",
      "plotArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Office in IT Park/SEZ": {
    Sale: [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "areaIn",
      "carpetArea",
      "coveredArea",
      "plotArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Commercial Shop": {
    Sale: [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "personalWashroom",
      "pantryCafeteria",
      "cornerShop",
      "isMainRoadFacing",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "widthOfEntrance",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "personalWashroom",
      "pantryCafeteria",
      "lockinPeriod",
      "cornerShop",
      "isMainRoadFacing",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "widthOfEntrance",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Commercial Showroom": {
    Sale: [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "isMainRoadFacing",
      "cornerShowroom",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "widthOfEntrance",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "lockinPeriod",
      "cornerShop",
      "isMainRoadFacing",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "widthOfEntrance",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Commercial Land": {
    Sale: [
      "projectName",
      "landZone",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "bookingOrTokenAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
    ],
  },
  "Warehouse/Godown": {
    Sale: [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Industrial Land": {
    Sale: [
      "projectName",
      "landZone",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "anyConstructionDone",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
    ],
  },
  "Industrial Building": {
    Sale: [
      "projectName",
      "landZone",
      "totalFloors",
      "areaIn",
      "coveredArea",
      "plotArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "totalFloors",
      "areaIn",
      "coveredArea",
      "plotArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Industrial Shed": {
    Sale: [
      "projectName",
      "landZone",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Agricultural Land": {
    Sale: [
      "projectName",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
    ],
  },
  "Farm House": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "totalFloors",
      "furnishedStatus",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "bedrooms",
      "bathrooms",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
};

export const step2FormFields = {
  youtubeLink: {
    key: "youtubeLink",
    type: "text",
    label: "Youtube Video Link",
    value: "",
  },
  overlooking: {
    key: "overlooking",
    type: "checkbox",
    label: "Overlooking",
    options: ["Garden/Park", "Pool", "Main Road", "Creek View"],
    value: "",
  },
  carParking: {
    key: "carParking",
    type: "radio",
    label: "Car Parking",
    options: ["Covered", "Open", "None"],
    value: "",
  },
  multiUnitAvai: {
    key: "multiUnitAvai",
    type: "radio",
    label: "Multiple Units Available(Jodi Flats)",
    options: ["Yes", "No"],
    value: "",
  },
  availOfWater: {
    key: "availOfWater",
    type: "select",
    label: "Availability Of Water",
    options: ["1 Hour", "2 Hours", "6 Hours", "12 Hours", "24 Hours"],
    value: "",
  },
  statusOfElec: {
    key: "statusOfElec",
    type: "select",
    label: "Status Of Electricity",
    options: [
      "No/Rare Powercut",
      "Less Than 2 Hours Powercut",
      "2 To 4 Hours Powercut",
      "4 To 6 Hours Powercut",
      "Over 6 Hours Powercut",
    ],
    value: "",
  },
  ownershipStatus: {
    key: "ownershipStatus",
    type: "select",
    label: "Ownership Status",
    options: [
      "Freehold",
      "Leasehold",
      "Power Of Attorney",
      "Co-operative Society",
    ],
    value: "",
  },
  plotApprovalAuthority: {
    key: "plotApprovalAuthority",
    type: "radio",
    label: "Plot Approval Authority",
    options: ["Yes", "No"],
    value: "",
  },
  approvedBy: {
    key: "approvedBy",
    type: "select",
    label: "Approved by",
    options: [
      "Municipal Corporation of Greater Mumbai",
      "Mumbai Metropolitan Region Development Authority",
      "Developer",
      "Maharashtra Housing and Area Development Authority",
      "Ramanagara–Channapatna Urban Development Authority",
      "RWA/Co-operative Housing Society",
      "City Municipal Corporation",
      "Development Authority",
      "Power Of Attorney",
      "Co-operative Society",
    ],
    hide: true,
    value: "",
  },
  connectivity: {
    key: "connectivity",
    type: "checkbox",
    label: "Connectivity",
    options: ["Railway", "Airport", "Metro", "Road"],
    value: "",
  },
  // connectivityWithin: {
  //   key: "connectivityWithin",
  //   type: "checkbox",
  //   label: "Connectivity Within",
  //   options: ["Within 2 km", "Within 5 km", "Within 10 km"],
  //   value: "",
  // },
  within2km: {
    key: "within2km",
    type: "checkbox",
    label: "Connectivity Within 2 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
    value: "",
  },
  within5km: {
    key: "within5km",
    type: "checkbox",
    label: "Connectivity Within 5 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
    value: "",
  },
  within10km: {
    key: "within10km",
    type: "checkbox",
    label: "Connectivity Within 10 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
    value: "",
  },
  flooring: {
    key: "flooring",
    type: "radio",
    label: "Flooring",
    options: [
      "Ceramic Tiles",
      "Granite",
      "Marble",
      "Marbonite",
      "Mosaic",
      "Normal Tiles/Kotah Stone",
      "Vitrified",
      "Wooden",
    ],
    value: "",
  },
  amenities: {
    key: "amenities",
    type: "checkbox",
    label: "Amenities",
    options: [
      "Air Conditioned",
      "Banquet Hall",
      "Bar/Lounge",
      "Cafeteria/Food Court",
      "Club House",
      "Concierge Services",
      "Conference Room",
      "DTH Television Facility",
      "Downtown",
      "Fingerprint Access",
      "Fireplace",
      "Full Glass Wall",
      "Golf Course",
      "Gymnasium",
      "Health club with Steam / Jaccuzi",
      "Helipad",
      "Hilltop",
      "House help accommodation",
      "Intercom Facility",
      "Internet/Wi-Fi Connectivity",
      "Island Kitchen Layout",
      "Jogging and Strolling Track",
      "Laundry Service",
      "Lift",
      "Maintenance Staff",
      "Outdoor Tennis Courts",
      "Park",
      "Piped Gas",
      "Power Back Up",
      "Private Garage",
      "Private Terrace/Garden",
      "Private jaccuzi",
      "Private pool",
      "RO Water System",
      "Rain Water Harvesting",
      "Reserved Parking",
      "Sea facing",
      "Security",
      "Service/Goods Lift",
      "Sky Villa",
      "Water Storage",
      "Water Front",
      "Visitor Parking",
      "Skyline View",
      "Smart Home",
      "Swimming Pool",
      "Vaastu Compliant",
      "Waste Disposal",
      "Theme based Architectures",
      "Wrap Around Balcony",
      "Solar Heating",
      "Solar Panel",
      "Garbage Duct",
    ],
    value: "",
  },
  extraAmenities: {
    key: "extraAmenities",
    type: "text",
    multiLine: 3,
    label: "Extra Amenities",
    value: "",
  },
  interestingPropertyDetails: {
    key: "interestingPropertyDetails",
    type: "text",
    multiLine: 3,
    label: "Interesting Property Details",
    value: "",
  },
  landmarksAndNeighbourhood: {
    key: "landmarksAndNeighbourhood",
    type: "text",
    multiLine: 3,
    label: "Landmarks & Neighbourhood",
    value: "",
  },
};

export const imgFields = {
  "Flat/Apartment": [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Residential House": [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  Villa: [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Builder Floor Apartment": [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  Penthouse: [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Studio Apartment": [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Service Apartment": [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Residential Land/Plot": [
    "Main Image",
    "Site View",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Commercial Office Space": [
    "Main Image",
    "Exterior View",
    "Common Area",
    "Washrooms",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Office in IT Park/SEZ": [
    "Main Image",
    "Exterior View",
    "Common Area",
    "Washrooms",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Commercial Shop": [
    "Main Image",
    "Exterior View",
    "Common Area",
    "Washrooms",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Commercial Showroom": [
    "Main Image",
    "Exterior View",
    "Common Area",
    "Washrooms",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Commercial Land": [
    "Main Image",
    "Site View",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Warehouse/Godown": [
    "Main Image",
    "Site View",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Industrial Land": [
    "Main Image",
    "Site View",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Industrial Building": [
    "Main Image",
    "Exterior View",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Industrial Shed": [
    "Main Image",
    "Exterior View",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Agricultural Land": [
    "Main Image",
    "Site View",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
  "Farm House": [
    "Main Image",
    "Exterior View",
    "Living Room",
    "Bedrooms",
    "Bathrooms",
    "Kitchen",
    "Floor Plan",
    "Master Plan",
    "Location Map",
    "Brochure",
    "Others",
  ],
};
